<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Chris Turner" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="modeling" class="section level1">
<h1>Modeling</h1>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<p>A knitted R Markdown document (preferably HTML) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on the due date. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(…) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). You can copy the set-up chunk in Project2.Rmd: I have gone ahead and set a few for you (such as disabling warnings and package-loading messages when knitting)!</p>
</div>
<div id="find-data" class="section level2">
<h2>Find data:</h2>
<p><a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a></p>
</div>
<div id="guidelines-and-rubric" class="section level2">
<h2>Guidelines and Rubric</h2>
<ul>
<li><strong>0. (5 pts)</strong> Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph. What are they measuring? How many observations?</li>
</ul>
<pre class="r"><code>collegedist_tidy &lt;- read.csv(&quot;collegedist.csv&quot;)</code></pre>
<p><em>My dataset describes the distances between colleges and high school students’ homes in 1980. There are 4,739 observations and 14 variables. The dataset included variables such as the gender and ethnicity of the students, as well as their base year composite test scores (“score”). The state hourly wage in manufacturing in 1980 was included as well. The fcollege and mcollege variables indicate whether or not the student’s father and mother are college graduates, respectively. Whether or not the student’s family owned a home was also included as well as the family income. The region in which the student lived was included as well, in addition to the county’s unemployment rate in 1980 and the average tuition for a 4-year college in that state.</em></p>
<ul>
<li><strong>1. (15 pts)</strong> Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all is unreasonable or doesn’t make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss some of the MANOVA assumptions and whether or not they are likely to have been met here (no need for anything too in-depth) (2).</li>
</ul>
<pre class="r"><code>library(dplyr)
library(mvtnorm)
library(ggExtra)

collegedist &lt;- collegedist_tidy
set.seed(1234)
dplyr::sample_n(collegedist, 10)</code></pre>
<pre><code>## X gender ethnicity score fcollege mcollege home urban
unemp wage distance tuition education
## 1 1004 female other 56.16 no no yes no 4.0 9.68 5.0
1.09353 15
## 2 623 female other 43.58 no yes yes no 7.5 9.96 0.2
1.40416 14
## 3 2693 female other 51.39 no no yes no 6.2 10.51 5.0
0.82448 16
## 4 934 female afam 51.31 no no no no 6.3 7.33 2.0 0.65589
12
## 5 7001 female other 59.56 no no no yes 4.3 8.89 1.0
0.25751 12
## 6 2948 female hispanic 43.82 no no yes yes 10.8 9.92 0.4
0.45497 12
## 7 2146 male other 38.27 no no yes no 14.0 12.15 3.5
1.16628 12
## 8 3175 female afam 57.89 no no yes no 8.2 7.54 1.2
0.81871 12
## 9 2774 male other 49.71 no no yes no 4.3 9.73 10.5
0.77829 14
## 10 2374 male other 54.54 yes yes yes no 6.9 10.28 0.5
0.93187 17
## income region
## 1 low other
## 2 low other
## 3 low other
## 4 low other
## 5 low west
## 6 low other
## 7 low other
## 8 low other
## 9 low other
## 10 high other</code></pre>
<pre class="r"><code>#MANOVA
man1 &lt;- manova(cbind(score, tuition, wage)~gender, data=collegedist)
summary(man1)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## gender 1 0.0068034 10.812 3 4735 4.464e-07 ***
## Residuals 4737
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man1)</code></pre>
<pre><code>## Response score :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## gender 1 2306 2305.89 30.642 3.27e-08 ***
## Residuals 4737 356471 75.25
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response tuition :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## gender 1 0.04 0.044479 0.3858 0.5345
## Residuals 4737 546.07 0.115278
##
## Response wage :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## gender 1 6.3 6.3282 3.5101 0.06106 .
## Residuals 4737 8540.2 1.8029
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>pairwise.t.test(collegedist$score, collegedist$gender, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  collegedist$score and collegedist$gender 
## 
##      female 
## male 3.3e-08
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(collegedist$tuition, collegedist$gender, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  collegedist$tuition and collegedist$gender 
## 
##      female
## male 0.53  
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(collegedist$wage, collegedist$gender, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  collegedist$wage and collegedist$gender 
## 
##      female
## male 0.061 
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>#Type I error rate = 0.3016627
1-0.95^7</code></pre>
<pre><code>## [1] 0.3016627</code></pre>
<pre class="r"><code>#Bonferroni correction = 0.007142857
0.05/7</code></pre>
<pre><code>## [1] 0.007142857</code></pre>
<p><em>The overall MANOVA is significant. 1 MANOVA, 3 ANOVA, and 3 t-tests were performed. The probability of at least one type I error was 0.3016627. After adjusting the significance level using the Bonferroni correction, it is 0.007142857. Male and female students seem to differ significantly in terms of base year composite test scores, but do not differ significantly in terms of the average tuition for a 4-year college near them or their state’s hourly wage in manufacturing in 1980. MANOVA assumptions include random sampling, independent observations, multivariate normality of DVs, homogeneity of within-group covariance matrices, linear relationships among DVs, no extreme univariate or multivariate outliers, and no multicollinearity; in order words, DVs cannot be too correlated with each other. These assumptions are most likely not met.</em></p>
<ul>
<li><strong>2. (10 pts)</strong> Perform some kind of randomization test on your data (that makes sense). The statistic can be anything you want (mean difference, correlation, F-statistic/ANOVA, chi-squared), etc. State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</li>
</ul>
<pre class="r"><code>library(tidyverse)
set.seed(348)
head(collegedist)</code></pre>
<pre><code>## X gender ethnicity score fcollege mcollege home urban
unemp wage distance tuition education
## 1 1 male other 39.15 yes no yes yes 6.2 8.09 0.2 0.88915
12
## 2 2 female other 48.87 no no yes yes 6.2 8.09 0.2
0.88915 12
## 3 3 male other 48.74 no no yes yes 6.2 8.09 0.2 0.88915
12
## 4 4 male afam 40.40 no no yes yes 6.2 8.09 0.2 0.88915
12
## 5 5 female other 40.48 no no no yes 5.6 8.09 0.4 0.88915
13
## 6 6 male other 54.71 no no yes yes 5.6 8.09 0.4 0.88915
12
## income region
## 1 high other
## 2 low other
## 3 low other
## 4 low other
## 5 low other
## 6 low other</code></pre>
<pre class="r"><code>collegedist %&gt;% group_by(gender) %&gt;% summarize(means=mean(unemp)) %&gt;% summarize(&#39;mean_diff&#39;=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   mean_diff
##       &lt;dbl&gt;
## 1    -0.158</code></pre>
<pre class="r"><code>rand_dist &lt;- vector()
for(i in 1:5000){
  new &lt;- data.frame(unemp=sample(collegedist$unemp), gender=collegedist$gender)
  rand_dist[i] &lt;- mean(new[new$gender==&quot;female&quot;,]$unemp)- mean(new[new$gender==&quot;male&quot;,]$unemp)
}
{hist(rand_dist,main=&quot;&quot;, ylab=&quot;&quot;); abline(v = c(-0.158, 0.158), col=&quot;red&quot;)}</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#two-tailed p value 
mean(rand_dist&gt;0.158 | rand_dist&lt; -0.158)</code></pre>
<pre><code>## [1] 0.051</code></pre>
<pre class="r"><code>t.test(data=collegedist, unemp~gender)</code></pre>
<pre><code>##
## Welch Two Sample t-test
##
## data: unemp by gender
## t = 1.9603, df = 4614.2, p-value = 0.05003
## alternative hypothesis: true difference in means is not
equal to 0
## 95 percent confidence interval:
## -1.761696e-05 3.152045e-01
## sample estimates:
## mean in group female mean in group male
## 7.668346 7.510753</code></pre>
<p><em>Ho: mean unemployment rate is the same for females vs males. Ha: mean unemployment rate is different for females vs males. The p-value of 0.051 indicates that the test is not statistically significant and indicates strong evidence in support of the null hypothesis. Therefore, we fail to reject the null hypothesis and reject the alternative hypothesis, concluding that the mean unemployment rate is different for females vs males.</em></p>
<ul>
<li><strong>3. (40 pts)</strong> Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.</li>
</ul>
<pre class="r"><code>library(lmtest)
library(sandwich)
fit&lt;-lm(score ~ tuition + wage, data = collegedist)
summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = score ~ tuition + wage, data = collegedist)
##
## Residuals:
## Min 1Q Median 3Q Max
## -21.4584 -6.7292 0.2362 6.6840 21.6165
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 43.57360 0.89304 48.793 &lt; 2e-16 ***
## tuition 2.64574 0.38822 6.815 1.06e-11 ***
## wage 0.54315 0.09814 5.535 3.29e-08 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 8.602 on 4736 degrees of
freedom
## Multiple R-squared: 0.02318, Adjusted R-squared: 0.02277
## F-statistic: 56.2 on 2 and 4736 DF, p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>ggplot(collegedist, aes(x=tuition + wage, y=score, group = gender)) + geom_point(aes(color=gender)) + geom_smooth(method=&quot;lm&quot;, formula=y~1, se=F, fullrange=T, aes(color=gender)) + theme(legend.position=c(0.9, 0.19)) + xlab(&quot;&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>resids &lt;- fit$residuals
fitvals &lt;- fit$fitted.values
ggplot() + geom_point(aes(fitvals, resids)) + geom_hline(yintercept=0, color=&#39;red&#39;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>par(mfrow=c(1,2));hist(resids);qqnorm(resids);qqline(resids, col=&#39;red&#39;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>coeftest(fit, vcov=vcovHC(fit)) </code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 43.573602 0.886536 49.1504 &lt; 2.2e-16 ***
## tuition 2.645743 0.390475 6.7757 1.389e-11 ***
## wage 0.543148 0.097813 5.5529 2.962e-08 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = score ~ tuition + wage, data = collegedist)
##
## Residuals:
## Min 1Q Median 3Q Max
## -21.4584 -6.7292 0.2362 6.6840 21.6165
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 43.57360 0.89304 48.793 &lt; 2e-16 ***
## tuition 2.64574 0.38822 6.815 1.06e-11 ***
## wage 0.54315 0.09814 5.535 3.29e-08 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 8.602 on 4736 degrees of
freedom
## Multiple R-squared: 0.02318, Adjusted R-squared: 0.02277
## F-statistic: 56.2 on 2 and 4736 DF, p-value: &lt; 2.2e-16</code></pre>
<p><em>The coefficient estimate for tuition shows that for every 1000 USD increase in tuition, the score increases by 2.64574. The coefficient estimate for wage shows that for every $1 increase in hourly wage on average, the score increases by 0.54315. The standard error for the intercept is 0.89304. The standard error for tuition is 0.38822. The standard error for wage is 0.09814. From the graph, it appears that linearity, normality, and homoskedasticity look fine. THe standard error did not differ. The new standard error for the intercept is 0.886536. The new standard error for tuition is 0.390475. The new standard error for wage is 0.097813. The proportion of the variation in the outcome of the model explained is 0.02277.</em></p>
<ul>
<li><strong>4. (5 pts)</strong> Rerun same regression model (with the interaction), but this time compute bootstrapped standard errors (either by resampling observations or residuals). Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</li>
</ul>
<pre class="r"><code>boot_dat &lt;- sample_frac(collegedist, replace=T)
samp_distn &lt;- replicate(5000, {
  boot_dat &lt;- sample_frac(collegedist, replace=T)
  fit &lt;- lm(score ~ tuition + wage, data=boot_dat)
  coef(fit)
})
samp_distn %&gt;% t %&gt;% as.data.frame %&gt;% summarize_all(sd)</code></pre>
<pre><code>##   (Intercept)   tuition       wage
## 1   0.8926046 0.3870123 0.09890067</code></pre>
<p><em>The new intercept is 0.8926046. The new standard error for tuition is 0.3870123. The new standard error for wage is 0.09890067.</em></p>
<ul>
<li><strong>5. (30 pts)</strong> Fit a logistic regression model predicting a binary variable (if you don’t have one, make/get one) from at least two explanatory variables (interaction not necessary).</li>
</ul>
<pre class="r"><code>library(tidyverse)
library(lmtest)
library(plotROC)
data &lt;- collegedist %&gt;% mutate(y=ifelse(gender==&quot;female&quot;,1,0))
data$gender &lt;- factor(data$gender, levels=c(&quot;female&quot;, &quot;male&quot;))
head(data)</code></pre>
<pre><code>## X gender ethnicity score fcollege mcollege home urban
unemp wage distance tuition education
## 1 1 male other 39.15 yes no yes yes 6.2 8.09 0.2 0.88915
12
## 2 2 female other 48.87 no no yes yes 6.2 8.09 0.2
0.88915 12
## 3 3 male other 48.74 no no yes yes 6.2 8.09 0.2 0.88915
12
## 4 4 male afam 40.40 no no yes yes 6.2 8.09 0.2 0.88915
12
## 5 5 female other 40.48 no no no yes 5.6 8.09 0.4 0.88915
13
## 6 6 male other 54.71 no no yes yes 5.6 8.09 0.4 0.88915
12
## income region y
## 1 high other 0
## 2 low other 1
## 3 low other 0
## 4 low other 0
## 5 low other 1
## 6 low other 0</code></pre>
<pre class="r"><code>data &lt;- na.omit(data)
fit2&lt;- glm(y~score + tuition, data=data, family = &quot;binomial&quot;)
coeftest(fit2)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) 1.1385664 0.1814456 6.2750 3.497e-10 ***
## score -0.0186488 0.0034079 -5.4721 4.446e-08 ***
## tuition 0.0084822 0.0869838 0.0975 0.9223
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>probs &lt;- predict(fit2, type=&quot;response&quot;)
table(predict=as.numeric(probs&gt;0.5), truth=data$y) %&gt;% addmargins</code></pre>
<pre><code>##        truth
## predict    0    1  Sum
##     0    332  264  596
##     1   1807 2336 4143
##     Sum 2139 2600 4739</code></pre>
<pre class="r"><code>class_diag&lt;- function(probs, truth){
  #CONFUSION MATRIX: CALLCULATE ACCURACY, TPR, TNR, PPV
  probs &lt;- na.omit(probs)
  tab &lt;- table(factor(probs&gt;0.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]
  f1=2*(sens*ppv)/(sens+ppv)
  
  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  
  #CALCULATE EXACT AUC
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  n &lt;- length(TPR)
  auc &lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,f1,auc)
}
class_diag(probs, data$y)</code></pre>
<pre><code>## acc sens spec ppv f1 auc
## 1 0.562988 0.8984615 0.1552127 0.5638426 0.6928667
0.5469405</code></pre>
<pre class="r"><code>data$logit&lt;-predict(fit2, type=&quot;link&quot;)
data%&gt;%ggplot() + geom_density(aes(logit, color=gender, fill=gender), alpha=0.4) + theme(legend.position=c(0.85, 0.85)) + geom_vline(xintercept=1)+xlab(&quot;logit (log-odds)&quot;) + geom_rug(aes(logit, color=gender))</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ROCplot&lt;-ggplot(data)+geom_roc(aes(d=gender, m=probs), n.cuts=0)
ROCplot</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.4530623</code></pre>
<p><em>Because the coefficient estimates in context are negative for score and positive for tuition, it is likely that the two predictors significantly increase the probability of the gender of the student being male. Accuracy=0.562988. Sensitivity (TPR)=0.8984615. Specificity (TNR)=0.1552127. Precision (PPV)=0.5638426. AUC=0.5469405.
The AUC from the ROC plot is 0.04530623. The AUC decreased.</em></p>
<ul>
<li><strong>6. (25 pts)</strong> Perform a logistic regression predicting the same binary response variable from <em>ALL</em> of the rest of your variables (the more, the better!)</li>
</ul>
<p>**</p>
</div>
<div id="where-do-i-find-data-again" class="section level2">
<h2>Where do I find data again?</h2>
<p>You can choose ANY datasets you want that meet the above criteria for variables and observations. You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat, or whatever. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn’t end up being that big of a deal.</p>
<p>If you are totally clueless and have no direction at all, log into the server and type</p>
<pre class="r"><code>data(package = .packages(all.available = TRUE))</code></pre>
<p>This will print out a list of <strong>ALL datasets in ALL packages</strong> installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much… To start with something more manageable, just run the command on your own computer, or just run <code>data()</code> to bring up the datasets in your current environment. To read more about a dataset, do <code>?packagename::datasetname</code>.</p>
<p>If it is easier for you, and in case you don’t have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
<ul>
<li><p>A good package to download for fun/relevant data is <code>fivethiryeight</code>.
Run <code>install.packages("fivethirtyeight"),</code> load the packages with <code>library(fivethirtyeight)</code>, run <code>data()</code>, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc.</p></li>
<li><p>If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above</p></li>
<li><p>However, you <em>emphatically DO NOT</em> have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: <a href="https://www.wunderground.com/history/" class="uri">https://www.wunderground.com/history/</a>). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!</p></li>
<li><p>Here is a curated list of interesting datasets (read-only spreadsheet format): <a href="https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit" class="uri">https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit</a></p></li>
<li><p>Here is another great compilation of datasets: <a href="https://github.com/rfordatascience/tidytuesday" class="uri">https://github.com/rfordatascience/tidytuesday</a></p></li>
<li><p>Here is the UCI Machine Learning Repository: <a href="https://archive.ics.uci.edu/ml/index.php" class="uri">https://archive.ics.uci.edu/ml/index.php</a></p>
<ul>
<li>See also <a href="https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data" class="uri">https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data</a></li>
</ul></li>
<li><p>Here is another good general place to look: <a href="https://www.kaggle.com/datasets" class="uri">https://www.kaggle.com/datasets</a></p></li>
<li><p>To help narrow your search down or to see interesting variable ideas, check out <a href="https://www.tylervigen.com/spurious-correlations" class="uri">https://www.tylervigen.com/spurious-correlations</a>. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!</p></li>
<li><p>If you are interested in medical data, check out www.countyhealthrankings.org</p></li>
<li><p>If you are interested in scraping UT data, they make <em>loads</em> of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: <a href="https://reports.utexas.edu/statistical-handbook" class="uri">https://reports.utexas.edu/statistical-handbook</a></p></li>
</ul>
<div id="broader-data-sources" class="section level5">
<h5>Broader data sources:</h5>
<p><a href="www.data.gov">Data.gov</a> 186,000+ datasets!</p>
<p><a href="Social%20Explorer">Social Explorer</a> is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.</p>
<p><a href="www.bls.gov">U.S. Bureau of Labor Statistics</a></p>
<p><a href="www.census.gov">U.S. Census Bureau</a></p>
<p><a href="www.gapminder.org/data">Gapminder</a>, data about the world.</p>
<p>…</p>
</div>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
